### PR TITLE
Create index.md

### PR DESCRIPTION
**Pull request by aestriex**

### CODE REVIEW

**Review by Ashirg-ch — COMMENTED** [review]
LGTM

**Comment by aestriex** [comment]
> LGTM

What does that mean @Ashirg-ch?

**Comment by Ashirg-ch** [comment]
> > LGTM
> 
> What does that mean @Ashirg-ch?

Looks Good To Merge

**Comment by Lagforce2157** [comment]
Go for it.

**Review by Lagforce2157 — APPROVED** [review]
Looks fine

**Pull request merged**
